import type { Program } from '../types';

export const mockPrograms: Program[] = [
  {
    id: 1,
    title: 'Collège – Cycle Fondamental',
    slug: 'college-cycle-fondamental',
    category: 'GENERAL',
    level: 'Collège',
    duration: '4 ans (6ème → 3ème)',
    description: 'Le cycle collège au CERIN offre une formation générale solide, préparant les élèves au baccalauréat avec des méthodes pédagogiques innovantes et un accompagnement personnalisé.',
    objectives: 'Acquérir les fondamentaux académiques, développer l\'esprit critique et préparer l\'orientation vers le lycée ou les filières professionnelles.',
    curriculum: 'Français, Mathématiques, Sciences physiques, SVT, Histoire-Géographie, Anglais, Éducation civique, Arts, EPS, Informatique',
    career_opportunities: 'Poursuite vers le Lycée Général, Lycée Technique ou Formation Professionnelle.',
    admission_requirements: 'Certificat de scolarité, dernier bulletin, extrait de naissance, photo d\'identité.',
    tuition: '150 000 FCFA / trimestre',
    image: { url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80' },
    featured: true,
    published_at: '2024-01-01T00:00:00.000Z',
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 2,
    title: 'Lycée Général',
    slug: 'lycee-general',
    category: 'GENERAL',
    level: 'Lycée',
    duration: '3 ans (Seconde → Terminale)',
    description: 'Le Lycée Général au CERIN prépare les élèves au Baccalauréat avec excellence. Nos programmes sont alignés sur les standards nationaux et internationaux.',
    objectives: 'Préparer le Baccalauréat avec les meilleures chances de réussite, développer les capacités d\'analyse et de synthèse.',
    curriculum: 'Français, Philosophie, Mathématiques, Physique-Chimie, SVT, Histoire-Géographie, Anglais, LV2, Économie, Informatique',
    career_opportunities: 'BTS, Licence, Master, Grandes Écoles.',
    admission_requirements: 'Diplôme du collège (BFEM ou équivalent), dossier scolaire.',
    tuition: '180 000 FCFA / trimestre',
    image: { url: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=800&q=80' },
    featured: true,
    published_at: '2024-01-01T00:00:00.000Z',
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 3,
    title: 'BTS Informatique',
    slug: 'bts-informatique',
    category: 'SUPERIEUR',
    level: 'Bac+2',
    duration: '2 ans',
    description: 'Formation technique approfondie en informatique : développement, réseaux, administration systèmes.',
    objectives: 'Formation supérieure permettant de concevoir, développer et maintenir des applications informatiques.',
    curriculum: 'Algorithmique, Programmation (Java, Python, JavaScript), Bases de données, Réseaux, Systèmes d\'exploitation, Cybersécurité, Projet tutoré, Stage en entreprise',
    career_opportunities: 'Développeur logiciel, Administrateur systèmes et réseaux, Analyste programmeur, Support technique.',
    admission_requirements: 'Baccalauréat (toutes séries), préférence pour les séries scientifiques et techniques.',
    tuition: '350 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80' },
    featured: true,
    published_at: '2024-01-15T00:00:00.000Z',
    created_at: '2024-01-15T00:00:00.000Z',
    updated_at: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 4,
    title: 'BTS Gestion Commerciale',
    slug: 'bts-gestion-commerciale',
    category: 'SUPERIEUR',
    level: 'Bac+2',
    duration: '2 ans',
    description: 'Formation aux techniques de commerce, de vente et de gestion commerciale.',
    objectives: 'Former des commerciaux et gestionnaires capables de développer les ventes et gérer une clientèle.',
    curriculum: 'Marketing, Techniques de vente, Gestion commerciale, Économie-Droit, Communication, Projet de création d\'entreprise',
    career_opportunities: 'Commercial, Chargé de clientèle, Responsable commercial, Chef de marché.',
    admission_requirements: 'Baccalauréat toutes séries.',
    tuition: '320 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80' },
    featured: false,
    published_at: '2024-01-15T00:00:00.000Z',
    created_at: '2024-01-15T00:00:00.000Z',
    updated_at: '2024-01-15T00:00:00.000Z',
  },
  {
    id: 5,
    title: 'Licence Informatique',
    slug: 'licence-informatique',
    category: 'SUPERIEUR',
    level: 'Bac+3',
    duration: '3 ans',
    description: 'Formation universitaire en informatique avec une approche théorique et pratique.',
    objectives: 'Maîtriser les concepts fondamentaux de l\'informatique et développer des compétences pratiques en programmation et analyse.',
    curriculum: 'Algorithmique avancée, Structures de données, Génie logiciel, Intelligence Artificielle, Cloud Computing, Stage de fin d\'études',
    career_opportunities: 'Ingénieur logiciel, Architecte systèmes, Data analyst, Chef de projet informatique.',
    admission_requirements: 'Bac+2 (BTS, DUT, Licence 2) en informatique ou domaine connexe.',
    tuition: '450 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80' },
    featured: true,
    published_at: '2024-02-01T00:00:00.000Z',
    created_at: '2024-02-01T00:00:00.000Z',
    updated_at: '2024-02-01T00:00:00.000Z',
  },
  {
    id: 6,
    title: 'Master Management et Stratégie',
    slug: 'master-management-strategie',
    category: 'SUPERIEUR',
    level: 'Bac+5',
    duration: '2 ans',
    description: 'Formation d\'excellence en management pour former les dirigeants de demain.',
    objectives: 'Développer une vision stratégique et opérationnelle pour piloter des organisations complexes.',
    curriculum: 'Stratégie d\'entreprise, Finance, Marketing stratégique, Ressources humaines, Leadership, Mémoire de recherche, Stage cadre',
    career_opportunities: 'Directeur général, Consultant senior, Directeur financier, Chef de projet stratégique.',
    admission_requirements: 'Licence (Bac+3) en sciences de gestion, économie ou équivalent. Dossier + entretien.',
    tuition: '600 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80' },
    featured: false,
    published_at: '2024-02-15T00:00:00.000Z',
    created_at: '2024-02-15T00:00:00.000Z',
    updated_at: '2024-02-15T00:00:00.000Z',
  },
  {
    id: 7,
    title: 'BTP – Bâtiment et Travaux Publics',
    slug: 'btp-batiment-travaux-publics',
    category: 'TECHNIQUE',
    level: 'Bac+2',
    duration: '2 ans',
    description: 'Formation technique dans les métiers du bâtiment et des travaux publics.',
    objectives: 'Maîtriser les techniques de construction, de lecture de plans et de gestion de chantier.',
    curriculum: 'Dessin technique, Matériaux de construction, Mécanique des sols, Topographie, Sécurité sur chantier, Stage pratique',
    career_opportunities: 'Conducteur de travaux, Dessinateur-projeteur, Chef de chantier, Technicien BTP.',
    admission_requirements: 'Baccalauréat série C, D ou technique.',
    tuition: '280 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80' },
    featured: false,
    published_at: '2024-03-01T00:00:00.000Z',
    created_at: '2024-03-01T00:00:00.000Z',
    updated_at: '2024-03-01T00:00:00.000Z',
  },
  {
    id: 8,
    title: 'Électrotechnique',
    slug: 'electrotechnique',
    category: 'TECHNIQUE',
    level: 'Bac+2',
    duration: '2 ans',
    description: 'Formation en électricité industrielle et maintenance électrique.',
    objectives: 'Installer, dépanner et maintenir les installations électriques industrielles et domestiques.',
    curriculum: 'Électricité, Électronique, Automatisme, Lecture de schémas, Normes électriques, Maintenance, Stage en entreprise',
    career_opportunities: 'Électricien industriel, Technicien de maintenance, Automaticien, Responsable d\'installation électrique.',
    admission_requirements: 'Baccalauréat toutes séries, préférence pour série C et technique.',
    tuition: '260 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80' },
    featured: false,
    published_at: '2024-03-01T00:00:00.000Z',
    created_at: '2024-03-01T00:00:00.000Z',
    updated_at: '2024-03-01T00:00:00.000Z',
  },
  {
    id: 9,
    title: 'Mécanique Automobile',
    slug: 'mecanique-automobile',
    category: 'TECHNIQUE',
    level: 'Bac+2',
    duration: '2 ans',
    description: 'Formation aux métiers de la mécanique automobile : entretien, réparation, diagnostic.',
    objectives: 'Diagnostiquer et réparer tous types de véhicules, maîtriser les outils de diagnostic moderne.',
    curriculum: 'Moteur thermique, Électricité automobile, Système de freinage, Suspension, Climatisation, Diagnostic électronique, Stage pratique',
    career_opportunities: 'Mécanicien automobile, Technicien diagnostic, Chef d\'atelier, Vendeur technique.',
    admission_requirements: 'Baccalauréat toutes séries, passion pour l\'automobile.',
    tuition: '270 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1485291571150-772bcfc10e80?auto=format&fit=crop&w=800&q=80' },
    featured: false,
    published_at: '2024-03-01T00:00:00.000Z',
    created_at: '2024-03-01T00:00:00.000Z',
    updated_at: '2024-03-01T00:00:00.000Z',
  },
  {
    id: 10,
    title: 'Maintenance des Systèmes Informatiques',
    slug: 'maintenance-systemes-informatiques',
    category: 'TECHNIQUE',
    level: 'Bac+2',
    duration: '2 ans',
    description: 'Former des techniciens capables de maintenir et dépanner les systèmes informatiques.',
    objectives: 'Assurer la maintenance préventive et curative des parcs informatiques.',
    curriculum: 'Assemblage PC, Systèmes d\'exploitation, Réseaux locaux, Maintenance hardware/software, Dépannage, Stage en entreprise',
    career_opportunities: 'Technicien de maintenance informatique, Technicien Helpdesk, Administrateur parc informatique.',
    admission_requirements: 'Baccalauréat toutes séries.',
    tuition: '250 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1580570157326-2bb278680be8?auto=format&fit=crop&w=800&q=80' },
    featured: false,
    published_at: '2024-03-15T00:00:00.000Z',
    created_at: '2024-03-15T00:00:00.000Z',
    updated_at: '2024-03-15T00:00:00.000Z',
  },
  {
    id: 11,
    title: 'Comptabilité et Gestion',
    slug: 'comptabilite-gestion',
    category: 'SUPERIEUR',
    level: 'Bac+2',
    duration: '2 ans',
    description: 'Formation aux métiers de la comptabilité, de la gestion et de la finance d\'entreprise.',
    objectives: 'Maîtriser les techniques comptables et la gestion financière des entreprises.',
    curriculum: 'Comptabilité générale, Comptabilité analytique, Fiscalité, Gestion financière, Droit des affaires, Logiciels comptables (Sage, QuickBooks)',
    career_opportunities: 'Comptable, Contrôleur de gestion, Auditeur, Directeur financier.',
    admission_requirements: 'Baccalauréat toutes séries.',
    tuition: '300 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80' },
    featured: false,
    published_at: '2024-03-15T00:00:00.000Z',
    created_at: '2024-03-15T00:00:00.000Z',
    updated_at: '2024-03-15T00:00:00.000Z',
  },
  {
    id: 12,
    title: 'Marketing Digital et Communication',
    slug: 'marketing-digital-communication',
    category: 'SUPERIEUR',
    level: 'Bac+3',
    duration: '3 ans',
    description: 'Formation aux métiers du marketing digital, de la communication et de la création de contenu.',
    objectives: 'Maîtriser les outils et stratégies du marketing digital pour développer la visibilité des entreprises.',
    curriculum: 'Marketing digital, Réseaux sociaux, SEO/SEA, Content marketing, Design graphique, Community management, Stage en entreprise',
    career_opportunities: 'Community manager, Chef de projet digital, Responsable marketing, Créateur de contenu.',
    admission_requirements: 'Baccalauréat toutes séries.',
    tuition: '400 000 FCFA / semestre',
    image: { url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80' },
    featured: true,
    published_at: '2024-04-01T00:00:00.000Z',
    created_at: '2024-04-01T00:00:00.000Z',
    updated_at: '2024-04-01T00:00:00.000Z',
  },
];
